### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by StuartIanNaylor** [Speaker-Identification/IdentifySpeakersNet#10]
```
sudo docker run --rm -p 5000:5000 yoso
 * Serving Flask app "demo/app.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing "fbank_net.demo.app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/fbank_net/demo/app.py", line 8, in <module>
    from .preprocessing import extract_fbanks
  File "/fbank_net/demo/preprocessing.py", line 1, in <module>
    import librosa
  File "/usr/local/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python3.6/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.6/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.6/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.6/site-packages/librosa/util/utils.py", line 15, in <module>
    from .decorators import deprecated
  File "/usr/local/lib/python3.6/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
```

**Comment by scrimpys** [comment]
Have the same issue... ubuntu 22.04
Any help appreciated.

**Comment by loopassembly** [comment]
I encountered the same issues while building the Docker image and was able to resolve them by making some updates to the Dockerfile. Below is the updated Dockerfile that worked for me:
https://github.com/loopassembly/You-Only-Speak-Once/blob/master/Dockerfile
